// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
/* eslint-disable */
import d_0_raw from "../../content/destinations/armenia.mdx";
const d_0: string = d_0_raw as unknown as string;
import d_1_raw from "../../content/destinations/greece.mdx";
const d_1: string = d_1_raw as unknown as string;

import p_0_raw from "../../content/posts/a-month-in-yerevan.mdx";
const p_0: string = p_0_raw as unknown as string;
import p_1_raw from "../../content/posts/digital-nomad-guide-to-yerevan.mdx";
const p_1: string = p_1_raw as unknown as string;
import p_2_raw from "../../content/posts/winter-in-athens.mdx";
const p_2: string = p_2_raw as unknown as string;

export type RawContent = {
  destinations: Record<string, string>;
  posts: Record<string, string>;
};
export const rawContent: RawContent = {
  destinations: {
    "armenia": d_0,
    "greece": d_1,
  },
  posts: {
    "a-month-in-yerevan": p_0,
    "digital-nomad-guide-to-yerevan": p_1,
    "winter-in-athens": p_2,
  },
};
