#!/usr/bin/env node
/**
 * Scans `content/` and generates a static import registry so all Markdown/MDX
 * is bundled into the build (works everywhere — Node, Cloudflare worker) with
 * zero runtime filesystem access.
 *
 * Regenerate after adding/removing content files: `node scripts/gen-content.mjs`
 * (also wired into `predev` / `prebuild`).
 */
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const contentDir = join(root, "content");
const outFile = join(root, "src", "lib", "content-registry.ts");

function list(rel) {
  const full = join(contentDir, rel);
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => f.endsWith(".mdx"))
    .sort();
}

function buildBlock(rel, varPrefix) {
  const files = list(rel);
  let imports = "";
  let map = "";
  files.forEach((f, i) => {
    const slug = f.replace(/\.mdx$/, "");
    const ident = `${varPrefix}${i}`;
    const identRaw = `${ident}_raw`;
    const importPath = `../../content/${rel}/${f}`;
    imports += `import ${identRaw} from ${JSON.stringify(importPath)};\n`;
    imports += `const ${ident}: string = ${identRaw} as unknown as string;\n`;
    map += `    ${JSON.stringify(slug)}: ${ident},\n`;
  });
  return { imports, map };
}

const dest = buildBlock("destinations", "d_");
const posts = buildBlock("posts", "p_");

const ts = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
/* eslint-disable */
${dest.imports}
${posts.imports}
export type RawContent = {
  destinations: Record<string, string>;
  posts: Record<string, string>;
};
export const rawContent: RawContent = {
  destinations: {
${dest.map}  },
  posts: {
${posts.map}  },
};
`;

writeFileSync(outFile, ts);
const destCount = Object.keys(dest).length;
const postFiles = list("posts");
console.log(
  `Generated ${outFile} — ${destCount} destination group, ${postFiles.length} post(s) imported as raw MDX strings.`
);